2017-05-05 01:17:51.035 [error] <0.349.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.351.0>) line 430
2017-05-05 01:17:51.065 [error] <0.349.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.351.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 01:17:51.067 [error] <0.304.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.349.0> exit with reason no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.351.0>) line 430 in context child_terminated
2017-05-05 01:25:14.063 [error] <0.366.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.368.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.370.0>) line 430
2017-05-05 01:25:14.066 [error] <0.366.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.368.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.370.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 01:25:14.067 [error] <0.304.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.366.0> exit with reason no function clause matching lasp_core:update(<<"source">>, state_orset, <0.368.0>, #Fun<lasp_distribution_backend.38.830585>, #Fun<lasp_distribution_backend.39.830585>, <0.370.0>) line 430 in context child_terminated
2017-05-05 02:18:21.635 [error] <0.349.0> gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.66903587>, #Fun<lasp_distribution_backend.39.66903587>, <0.351.0>) line 430
2017-05-05 02:18:21.673 [error] <0.349.0> CRASH REPORT Process lasp_distribution_backend with 2 neighbours exited with reason: no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.66903587>, #Fun<lasp_distribution_backend.39.66903587>, <0.351.0>) line 430 in gen_server:terminate/7 line 812
2017-05-05 02:18:21.675 [error] <0.304.0> Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.349.0> exit with reason no function clause matching lasp_core:update(<<"source">>, state_orset, <0.196.0>, #Fun<lasp_distribution_backend.38.66903587>, #Fun<lasp_distribution_backend.39.66903587>, <0.351.0>) line 430 in context child_terminated
2017-05-05 04:17:32.790 [error] <0.400.0> CRASH REPORT Process <0.400.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.791 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.400.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.791 [error] <0.402.0> CRASH REPORT Process <0.402.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.792 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.402.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.792 [error] <0.404.0> CRASH REPORT Process <0.404.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.792 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.404.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.793 [error] <0.406.0> CRASH REPORT Process <0.406.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.793 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.406.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.793 [error] <0.408.0> CRASH REPORT Process <0.408.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.794 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.408.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.794 [error] <0.410.0> CRASH REPORT Process <0.410.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.794 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.410.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.795 [error] <0.412.0> CRASH REPORT Process <0.412.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.795 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.412.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.796 [error] <0.414.0> CRASH REPORT Process <0.414.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.796 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.414.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.796 [error] <0.416.0> CRASH REPORT Process <0.416.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.797 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.416.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.797 [error] <0.418.0> CRASH REPORT Process <0.418.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.797 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.418.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.798 [error] <0.420.0> CRASH REPORT Process <0.420.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var({<<"set">>}, <0.351.0>) line 349
2017-05-05 04:17:32.798 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.420.0> exit with reason function_clause in context child_terminated
2017-05-05 04:17:32.798 [error] <0.353.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{{<<"set">>},#Fun<lasp_process.2.118998842>}],#Fun<lasp_process.3.118998842>,{<0.349.0>,#Fun<lasp_..>}]) at <0.420.0> exit with reason reached_max_restart_intensity in context shutdown
2017-05-05 04:17:32.799 [error] <0.304.0> Supervisor lasp_sup had child lasp_process_sup started with lasp_process_sup:start_link() at <0.353.0> exit with reason shutdown in context child_terminated
